#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.xyz"
EWW="eww -c $HOME/.config/eww/dashboard"
cmd="xdg-open"

if [[ "$1" == "--firefox" ]]; then
	${EWW} close-all && rm -rf "$FILE" && firefox &

elif [[ "$1" == "--whatsapp" ]]; then
	${EWW} close-all && rm -rf "$FILE" && $cmd "https://web.whatsapp.com" &

elif [[ "$1" == "--github" ]]; then
	${EWW} close-all && rm -rf "$FILE" && $cmd "https://github.com" &

elif [[ "$1" == "--reddit" ]]; then
	${EWW} close-all && rm -rf "$FILE" && $cmd "https://reddit.com" &

elif [[ "$1" == "--youtube" ]]; then
	${EWW} close-all && rm -rf "$FILE" && $cmd "https://youtube.com" &

elif [[ "$1" == "--discord" ]]; then
	${EWW} close-all && rm -rf "$FILE" && discord &

elif [[ "$1" == "--spotify" ]]; then
	${EWW} close-all && rm -rf "$FILE" && spotify &

elif [[ "$1" == "--twitter" ]]; then
	${EWW} close-all && rm -rf "$FILE" && $cmd "https://twitter.com" &
fi
